## Golden Globes

In [1]:
import numpy as np
import pandas as pd

In [17]:
go = pd.read_csv("golden_globe_awards.csv")
os = pd.read_csv("oscar_nominees_with_fixed_race.csv", index_col=0)
os.head()

,year_film,year_ceremony,ceremony,category,name,film,winner,race,fixed_race
id,,,,,,,,,
0,1927,1928,1,ACTOR IN A LEADING ROLE,Richard Barthelmess,The Noose,False,white,white
1,1927,1928,1,ACTOR IN A LEADING ROLE,Emil Jannings,The Last Command,True,white,white
2,1928,1929,2,ACTOR IN A LEADING ROLE,George Bancroft,Thunderbolt,False,white,white
3,1928,1929,2,ACTOR IN A LEADING ROLE,Warner Baxter,In Old Arizona,True,white,white
4,1928,1929,2,ACTOR IN A LEADING ROLE,Chester Morris,Alibi,False,white,white

In [18]:
go.head()

,year_film,year_award,ceremony,category,nominee,film,win
0,1943,1944,1,Best Performance by an Actress in a Supporting...,Katina Paxinou,For Whom The Bell Tolls,True
1,1943,1944,1,Best Performance by an Actor in a Supporting R...,Akim Tamiroff,For Whom The Bell Tolls,True
2,1943,1944,1,Best Director - Motion Picture,Henry King,The Song Of Bernadette,True
3,1943,1944,1,Picture,The Song Of Bernadette,NaN,True
4,1943,1944,1,Actress In A Leading Role,Jennifer Jones,The Song Of Bernadette,True

In [19]:
os = os[os['year_film']>1943]

In [20]:
os_actors = set(os.name.unique())
go_actors = set(go.nominee.unique())
len(go_actors - os_actors)

3486

In [21]:
# 806 actors in Golden Globes covered by Oscars
print(len(go_actors), len(os_actors), len(go_actors - os_actors), len(go_actors.intersection(os_actors)))

4292 1029 3486 806

In [22]:
go.columns = ['year_film', 'year_ceremony', 'ceremony','category','name','film','winner']
go.head()

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1943,1944,1,Best Performance by an Actress in a Supporting...,Katina Paxinou,For Whom The Bell Tolls,True
1,1943,1944,1,Best Performance by an Actor in a Supporting R...,Akim Tamiroff,For Whom The Bell Tolls,True
2,1943,1944,1,Best Director - Motion Picture,Henry King,The Song Of Bernadette,True
3,1943,1944,1,Picture,The Song Of Bernadette,NaN,True
4,1943,1944,1,Actress In A Leading Role,Jennifer Jones,The Song Of Bernadette,True

In [23]:
go = go.merge(os[['name','race','fixed_race']], how='left').drop_duplicates()
go.head()

,year_film,year_ceremony,ceremony,category,name,film,winner,race,fixed_race
0,1943,1944,1,Best Performance by an Actress in a Supporting...,Katina Paxinou,For Whom The Bell Tolls,True,NaN,NaN
1,1943,1944,1,Best Performance by an Actor in a Supporting R...,Akim Tamiroff,For Whom The Bell Tolls,True,NaN,NaN
2,1943,1944,1,Best Director - Motion Picture,Henry King,The Song Of Bernadette,True,white,white
3,1943,1944,1,Picture,The Song Of Bernadette,NaN,True,NaN,NaN
4,1943,1944,1,Actress In A Leading Role,Jennifer Jones,The Song Of Bernadette,True,white,white

In [24]:
go[['race','fixed_race']] = go[['race','fixed_race']].fillna(value='unknown')

In [25]:
go.head()

,year_film,year_ceremony,ceremony,category,name,film,winner,race,fixed_race
0,1943,1944,1,Best Performance by an Actress in a Supporting...,Katina Paxinou,For Whom The Bell Tolls,True,unknown,unknown
1,1943,1944,1,Best Performance by an Actor in a Supporting R...,Akim Tamiroff,For Whom The Bell Tolls,True,unknown,unknown
2,1943,1944,1,Best Director - Motion Picture,Henry King,The Song Of Bernadette,True,white,white
3,1943,1944,1,Picture,The Song Of Bernadette,NaN,True,unknown,unknown
4,1943,1944,1,Actress In A Leading Role,Jennifer Jones,The Song Of Bernadette,True,white,white

In [26]:
categories = ['Best Director - Motion Picture', 'Best Performance by an Actor in a Motion Picture - Drama',
              'Best Performance by an Actress in a Motion Picture - Drama',
              'Best Performance by an Actress in a Supporting Role in a Series, Limited Series or Motion Picture Made for Television',
       'Best Performance by an Actor in a Supporting Role in a Series, Limited Series or Motion Picture Made for Television',]

In [27]:
go_temp = go[go.category.isin(categories)]
go_temp.shape

(1561, 9)

In [13]:
go_temp.to_csv("golden_globe_awards_with_race_temp.csv", index=False)

In [34]:
go.category.unique()

array(['Best Performance by an Actress in a Supporting Role in any Motion Picture',
       'Best Performance by an Actor in a Supporting Role in any Motion Picture',
       'Best Director - Motion Picture', 'Picture',
       'Actress In A Leading Role', 'Actor In A Leading Role',
       'Promoting International Understanding',
       'Special Achievement Award', 'Best Screenplay - Motion Picture',
       'Best Original Score - Motion Picture',
       'New Star Of The Year - Actress', 'New Star Of The Year - Actor',
       'Juvenile Performance', 'Cinematography',
       'Foreign Film - English Language',
       'Best Motion Picture - Foreign Language',
       'Outstanding Use Of Color',
       'Best Performance by an Actress in a Motion Picture - Drama',
       'Best Performance by an Actor in a Motion Picture - Drama',
       'Best Performance by an Actor in a Motion Picture - Musical or Comedy',
       'New Star Of The Year',
       'Actress In A Leading Role - Musical Or Comedy',
       'Henrietta Award (World Film Favorites)', 'Cinematography - Color',
       'Cinematography - Black And White', 'Best Motion Picture - Drama',
       'Best Motion Picture - Musical or Comedy',
       'Henrietta Award (World Film Favorite)', 'Cecil B. deMille Award',
       'Documentary', 'Television Achievement',
       'Hollywood Citizenship Award',
       'New Foreign Star Of The Year - Actress',
       'New Foreign Star Of The Year - Actor',
       'Foreign Film - Foreign Language', 'Picture - Musical',
       'Picture - Comedy', 'Samuel Goldwyn International Award',
       'Famous Silent Filmstars', 'Best Original Song - Motion Picture',
       'Television Series', 'Actor In A Television Series',
       'Actress In A Television Series', 'Best Television Series - Drama',
       'Television Program', 'Television Producer/Director',
       'Television Series - Comedy', 'International News Coverage',
       'Television Series - Variety',
       'Best Television Series - Musical or Comedy',
       'Actor In A Television Series - Musical Or Comedy',
       'Actor In A Television Series - Drama',
       'Actress In A Television Series - Drama',
       'Actress In A Television Series - Musical Or Comedy',
       'Best Performance by an Actress In A Television Series - Drama',
       'Best Performance by an Actor In A Television Series - Drama',
       'Best Performance by an Actress in a Television Series - Musical or Comedy',
       'Best Performance by an Actor in a Television Series - Musical or Comedy',
       'Actor In A Supporting Role - Television Series',
       'Actress In A Supporting Role - Television Series',
       'Television Movie',
       'Actress In A Supporting Role - Series Or Television Movie',
       'Actress In A Leading Role - Drama Series Or Television Movie',
       'Actor In A Leading Role - Drama Series Or Television Movie',
       'Actor In A Leading Role - Musical Or Comedy Series Or Television Movie',
       'Actor In A Supporting Role - Series Or Television Movie',
       'Actress In A Leading Role - Musical Or Comedy Series Or Television Movie',
       'Best Performance by an Actress in a Motion Picture - Musical or Comedy',
       'Best Performance by an Actress in a Supporting Role in a Series, Limited Series or Motion Picture Made for Television',
       'Best Performance by an Actor in a Supporting Role in a Series, Limited Series or Motion Picture Made for Television',
       'Television Special - Variety Or Musical',
       'Best Television Limited Series or Motion Picture Made for Television',
       'Best Performance by an Actress in a Limited Series or a Motion Picture Made for Television',
       'Best Performance by an Actor in a Limited Series or a Motion Picture Made for Television',
       'Best Motion Picture - Animated', 'Carol Burnett Award'],
      dtype=object)

In [16]:
go_temp = pd.read_csv("golden_globe_awards_with_race_temp.csv")
go_temp.head()

,year_film,year_ceremony,ceremony,category,name,film,winner,race,fixed_race
0,1943,1944,1,Best Director - Motion Picture,Henry King,The Song Of Bernadette,True,unknown,unknown
1,1944,1945,2,Best Director - Motion Picture,Leo McCarey,Going My Way,True,white,white
2,1945,1946,3,Best Director - Motion Picture,Billy Wilder,The Lost Weekend,True,white,white
3,1946,1947,4,Best Director - Motion Picture,Frank Capra,It's A Wonderful Life,True,white,white
4,1947,1948,5,Best Director - Motion Picture,Elia Kazan,Gentleman's Agreement,True,white,white

In [28]:
go_temp[go_temp.race=='unknown']

,year_film,year_ceremony,ceremony,category,name,film,winner,race,fixed_race
293,1951,1952,9,Best Director - Motion Picture,Laslo Benedek,Death of a Salesman (1951),True,unknown,unknown
350,1952,1953,10,Best Director - Motion Picture,Cecil B. deMille,The Greatest Show On Earth,True,unknown,unknown
351,1952,1953,10,Best Director - Motion Picture,Richard Fleischer,The Happy Time,False,unknown,unknown
723,1957,1958,15,Best Performance by an Actress in a Motion Pic...,Marlene Dietrich,Witness for the Prosecution,False,unknown,unknown
865,1958,1959,16,Best Performance by an Actor in a Motion Pictu...,Robert Donat,"Inn of the Sixth Happiness, The",False,unknown,unknown
...,...,...,...,...,...,...,...,...,...
14028,2018,2019,76,Best Performance by an Actor in a Supporting R...,Henry Winkler,Barry,False,unknown,unknown
14266,2019,2020,77,Best Performance by an Actor in a Supporting R...,Stellan Skarsgård,Chernobyl,True,unknown,unknown
14271,2019,2020,77,Best Performance by an Actor in a Supporting R...,Kieran Culkin,Succession,False,unknown,unknown
14272,2019,2020,77,Best Performance by an Actor in a Supporting R...,Andrew Scott,Fleabag,False,unknown,unknown
14273,2019,2020,77,Best Performance by an Actor in a Supporting R...,Henry Winkler,Barry,False,unknown,unknown

In [4]:
go_temp.shape

(1555, 9)

## Emmy's