In [148]:
import numpy as np
import pandas as pd

In [149]:
a = pd.read_csv('oscar_nominees_with_fixed_race.csv')
a['category'].replace(["ACTRESS IN A LEADING ROLE"], "Actress In A Leading Role", inplace=True)
a['category'].replace(["ACTOR IN A LEADING ROLE"], "Actor In A Leading Role", inplace=True)
a['category'].replace(["ACTRESS IN A SUPPORTING ROLE"], "Supporting Actress In A Leading Role", inplace=True)
a['category'].replace(["ACTOR IN A SUPPORTING ROLE"], "Supporting Actor In A Leading Role", inplace=True)

a.head()

,id,year_film,year_ceremony,ceremony,category,name,film,winner,race,fixed_race
0,0,1927,1928,1,Actor In A Leading Role,Richard Barthelmess,The Noose,False,white,white
1,1,1927,1928,1,Actor In A Leading Role,Emil Jannings,The Last Command,True,white,white
2,2,1928,1929,2,Actor In A Leading Role,George Bancroft,Thunderbolt,False,white,white
3,3,1928,1929,2,Actor In A Leading Role,Warner Baxter,In Old Arizona,True,white,white
4,4,1928,1929,2,Actor In A Leading Role,Chester Morris,Alibi,False,white,white

In [150]:
b = pd.read_csv('golden_globe_merged.csv')
b.head()

,Unnamed: 0,Unnamed: 0.1,year_film,year_award,ceremony,category,nominee,film,win,single_award,race
0,0,0,1943,1944,1,Best Performance by an Actress in a Supporting...,Katina Paxinou,For Whom The Bell Tolls,True,True,White
1,1,1,1943,1944,1,Best Performance by an Actor in a Supporting R...,Akim Tamiroff,For Whom The Bell Tolls,True,True,White
2,2,4,1943,1944,1,Actress In A Leading Role,Jennifer Jones,The Song Of Bernadette,True,True,White
3,3,2197,1974,1975,32,Best Performance by an Actress in a Supporting...,Jennifer Jones,The Towering Inferno,False,True,White
4,4,5,1943,1944,1,Actor In A Leading Role,Paul Lukas,Watch On The Rhine,True,True,White

In [151]:
c = pd.read_csv('sag_merged.csv')
c.head()

,Unnamed: 0,Unnamed: 0.1,year_ceremony,category,name,film,winner,single_award,race
0,0,5,2020 - 26th Annual Screen Actors Guild Awards,FEMALE ACTOR IN A LEADING ROLE,CYNTHIA ERIVO,HARRIET,False,True,White
1,1,6,2020 - 26th Annual Screen Actors Guild Awards,FEMALE ACTOR IN A LEADING ROLE,SCARLETT JOHANSSON,MARRIAGE STORY,False,True,White
2,2,16,2020 - 26th Annual Screen Actors Guild Awards,FEMALE ACTOR IN A SUPPORTING ROLE,SCARLETT JOHANSSON,JOJO RABBIT,False,True,White
3,3,7,2020 - 26th Annual Screen Actors Guild Awards,FEMALE ACTOR IN A LEADING ROLE,LUPITA NYONG'O,US,False,True,Black
4,4,1699,2014 - 20th Annual,FEMALE SUPPORTING ROLE,LUPITA NYONG'O,12 YEARS A SLAVE,True,True,Black

In [152]:
acount = a.groupby(['year_ceremony', 'fixed_race', 'category']).count().race.rename('count').reset_index()
acount['award'] = 'oscars'
acount.head()

   year_ceremony fixed_race                   category  count   award
0           1928      white    Actor In A Leading Role      2  oscars
1           1928      white  Actress In A Leading Role      3  oscars
2           1929      white    Actor In A Leading Role      5  oscars
3           1929      white  Actress In A Leading Role      6  oscars
4           1929      white                  DIRECTING      6  oscars

In [153]:
b.groupby(['year_award', 'race', 'category']).count()

                                                                     Unnamed: 0  \
year_award race  category
1944       White Actor In A Leading Role                                      1
                 Actress In A Leading Role                                    1
                 Best Performance by an Actor in a Supporting Ro...           1
                 Best Performance by an Actress in a Supporting ...           1
1945       White Actor In A Leading Role                                      1
...                                                                         ...
2020       White Best Performance by an Actress in a Motion Pict...           5
                 Best Performance by an Actress in a Motion Pict...           4
                 Best Performance by an Actress in a Supporting ...           5
                 Best Performance by an Actress in a Supporting ...           4
                 Best Performance by an Actress in a Television ...           5

                                                                     Unnamed: 0.1  \
year_award race  category
1944       White Actor In A Leading Role                                        1
                 Actress In A Leading Role                                      1
                 Best Performance by an Actor in a Supporting Ro...             1
                 Best Performance by an Actress in a Supporting ...             1
1945       White Actor In A Leading Role                                        1
...                                                                           ...
2020       White Best Performance by an Actress in a Motion Pict...             5
                 Best Performance by an Actress in a Motion Pict...             4
                 Best Performance by an Actress in a Supporting ...             5
                 Best Performance by an Actress in a Supporting ...             4
                 Best Performance by an Actress in a Television ...             5

                                                                     year_film  \
year_award race  category
1944       White Actor In A Leading Role                                     1
                 Actress In A Leading Role                                   1
                 Best Performance by an Actor in a Supporting Ro...          1
                 Best Performance by an Actress in a Supporting ...          1
1945       White Actor In A Leading Role                                     1
...                                                                        ...
2020       White Best Performance by an Actress in a Motion Pict...          5
                 Best Performance by an Actress in a Motion Pict...          4
                 Best Performance by an Actress in a Supporting ...          5
                 Best Performance by an Actress in a Supporting ...          4
                 Best Performance by an Actress in a Television ...          5

                                                                     ceremony  \
year_award race  category
1944       White Actor In A Leading Role                                    1
                 Actress In A Leading Role                                  1
                 Best Performance by an Actor in a Supporting Ro...         1
                 Best Performance by an Actress in a Supporting ...         1
1945       White Actor In A Leading Role                                    1
...                                                                       ...
2020       White Best Performance by an Actress in a Motion Pict...         5
                 Best Performance by an Actress in a Motion Pict...         4
                 Best Performance by an Actress in a Supporting ...         5
                 Best Performance by an Actress in a Supporting ...         4
                 Best Performance by an Actress in a Television ...         5

                                                                     nominee  \
year_award race  category
1944       White Actor In A Leading Role                                   1
                 Actress In A Leading Role                                 1
                 Best Performance by an Actor in a Supporting Ro...        1
                 Best Performance by an Actress in a Supporting ...        1
1945       White Actor In A Leading Role                                   1
...                                                                      ...
2020       White Best Performance by an Actress in a Motion Pict...        5
                 Best Performance by an Actress in a Motion Pict...        4
                 Best Performance by an Actress in a Supporting ...        5
                 Best Performance by an Actress in a Supporting ...        4
                 Best Performance by an Actress in a Television ...        5

                                                                     film  \
year_award race  category
1944       White Actor In A Leading Role                                1
                 Actress In A Leading Role                              1
                 Best Performance by an Actor in a Supporting Ro...     1
                 Best Performance by an Actress in a Supporting ...     1
1945       White Actor In A Leading Role                                1
...                                                                   ...
2020       White Best Performance by an Actress in a Motion Pict...     5
                 Best Performance by an Actress in a Motion Pict...     4
                 Best Performance by an Actress in a Supporting ...     5
                 Best Performance by an Actress in a Supporting ...     4
                 Best Performance by an Actress in a Television ...     5

                                                                     win  \
year_award race  category
1944       White Actor In A Leading Role                               1
                 Actress In A Leading Role                             1
                 Best Performance by an Actor in a Supporting Ro...    1
                 Best Performance by an Actress in a Supporting ...    1
1945       White Actor In A Leading Role                               1
...                                                                  ...
2020       White Best Performance by an Actress in a Motion Pict...    5
                 Best Performance by an Actress in a Motion Pict...    4
                 Best Performance by an Actress in a Supporting ...    5
                 Best Performance by an Actress in a Supporting ...    4
                 Best Performance by an Actress in a Television ...    5

                                                                     single_award
year_award race  category
1944       White Actor In A Leading Role                                        1
                 Actress In A Leading Role                                      1
                 Best Performance by an Actor in a Supporting Ro...             1
                 Best Performance by an Actress in a Supporting ...             1
1945       White Actor In A Leading Role                                        1
...                                                                           ...
2020       White Best Performance by an Actress in a Motion Pict...             5
                 Best Performance by an Actress in a Motion Pict...             4
                 Best Performance by an Actress in a Supporting ...             5
                 Best Performance by an Actress in a Supporting ...             4
                 Best Performance by an Actress in a Television ...             5

[1277 rows x 8 columns]

In [154]:
b['fixed_race'] =  b.race.replace({"White [1]": 'white', 
                'Multiracial':'other',
                'Multiracial [1]':'other',
                'Multiracial [2]': 'other',
                'Asian/Indian': 'asian',
                'American Aborigine': 'other',
                'American Aborigine [1]': 'other',
                'e': 'other',
                'Middle Eastern':'White'}).str.lower()

In [155]:
b['category'] = b.apply(lambda row: row['category'].strip(), axis=1)
b['category'].replace(["Best Performance by an Actress in a Motion Picture - Drama", "Best Performance by an Actress in a Motion Picture - Musical or Comedy"], "Actress In A Leading Role", inplace=True)
b['category'].replace(["Best Performance by an Actor in a Motion Picture - Drama", "Best Performance by an Actor in a Motion Picture - Musical or Comedy"], "Actor In A Leading Role", inplace=True)
b['category'].replace(["Best Performance by an Actress in a Supporting Role in any Motion Picture"], "Supporting Actress In A Leading Role", inplace=True)
b['category'].replace(["Best Performance by an Actor in a Supporting Role in any Motion Picture"], "Supporting Actor In A Leading Role", inplace=True)

bcount = b.dropna().groupby(['year_award', 'fixed_race', 'category']).count().race.rename('count').reset_index()
bcount['award'] = 'golden globes'
bcount.columns = ['year_ceremony'] + list(bcount.columns[1:])
categories = ["Actress In A Leading Role", "Actor In A Leading Role", "Supporting Actress In A Leading Role", 
             "Supporting Actor In A Leading Role"]
bcount = bcount[bcount['category'].isin(categories)]
bcount['category'].value_counts()

Actor In A Leading Role                 129
Supporting Actor In A Leading Role      115
Supporting Actress In A Leading Role    111
Actress In A Leading Role               101
Name: category, dtype: int64

In [156]:
c['fixed_race'] = c.race.replace({"Middle Eastern": 'White',
               'Asian/Indian': 'Asian',
               'Multiracial': 'Other',
               'Multiracial [1]': 'Other',
               'Multiracial [2]': 'Other'}).str.lower()

In [157]:
c['year_ceremony'] = c.year_ceremony.apply(lambda x: x.split('-')[0]).astype(int)

In [158]:
c['category'] = c.apply(lambda row: row['category'].strip(), axis=1)
c['category'].replace(['FEMALE LEAD ROLE', 'FEMALE LEAD', 'FEMALE LEAD IN A MOTION PICTURE', 'FEMALE ACTOR IN A LEADING ROLE'], 'Actress In A Leading Role', inplace=True)
c['category'].replace(['MALE LEAD ROLE', 'MALE LEAD', 'MALE LEAD IN A MOTION PICTURE', 'MALE ACTOR IN A LEADING ROLE'],'Actor In A Leading Role' , inplace=True)
c['category'].replace(['FEMALE SUPPORTING ROLE', 'FEMALE SUPPORT', 'FEMALE SUPPORT IN A MOTION PICTURE',  'FEMALE ACTOR IN A SUPPORTING ROLE'], "Supporting Actress In A Leading Role", inplace=True)
c['category'].replace(['MALE SUPPORTING ROLE', 'MALE SUPPORT', 'MALE SUPPORT IN A MOTION PICTURE', 'MALE ACTOR IN A SUPPORTING ROLE'], "Supporting Actor In A Leading Role", inplace=True)

ccount = c.groupby(['year_ceremony','fixed_race', 'category']).count().race.rename('count').reset_index()
ccount['award'] = 'sag'
categories = ["Actress In A Leading Role", "Actor In A Leading Role", "Supporting Actress In A Leading Role", 
             "Supporting Actor In A Leading Role"]
ccount = ccount[ccount['category'].isin(categories)]

In [159]:
df = pd.concat([acount, bcount, ccount])
df.fixed_race.unique()

array(['white', 'asian', 'black', 'hispanic', 'other'], dtype=object)

In [125]:
df.to_csv('all_awards_race_year_count.csv', index=False)

In [126]:
df.groupby(['year_ceremony','fixed_race', 'award', 'category'])['count'].apply(lambda x: x.astype(int)/x.astype(int).sum())

0       1.0
0       1.0
1       1.0
2       1.0
2       1.0
       ...
1103    1.0
1105    1.0
1106    1.0
1116    1.0
1117    1.0
Name: count, Length: 1082, dtype: float64

In [127]:
# df.groupby(['year_ceremony','fixed_race', 'award'])['count'].apply(lambda x: x.astype(int)/x.astype(int).sum())
df.groupby(['year_ceremony','award', 'category'])['count'].apply(lambda x: x.astype(int)/x.astype(int).sum())

0       1.0
0       1.0
1       1.0
2       1.0
2       1.0
       ...
1103    0.1
1105    0.2
1106    0.8
1116    1.0
1117    0.8
Name: count, Length: 1082, dtype: float64

In [160]:
df['pct_race'] = df['count'] / df.groupby(['year_ceremony','award', 'category'])['count'].transform('sum')

In [129]:
df

,year_ceremony,fixed_race,category,count,award,pct_race
0,1928,white,ACTOR IN A LEADING ROLE,2,oscars,1.0
1,1928,white,ACTRESS IN A LEADING ROLE,3,oscars,1.0
2,1929,white,ACTOR IN A LEADING ROLE,5,oscars,1.0
3,1929,white,ACTRESS IN A LEADING ROLE,6,oscars,1.0
4,1929,white,DIRECTING,6,oscars,1.0
...,...,...,...,...,...,...
432,2020,hispanic,FEMALE ACTOR IN A SUPPORTING ROLE,1,sag,0.2
435,2020,white,FEMALE ACTOR IN A LEADING ROLE,4,sag,0.8
436,2020,white,FEMALE ACTOR IN A SUPPORTING ROLE,4,sag,0.8
440,2020,white,MALE ACTOR IN A LEADING ROLE,5,sag,1.0
441,2020,white,MALE ACTOR IN A SUPPORTING ROLE,4,sag,0.8

In [161]:
df.to_csv('all_awards_race_year_count_latest.csv', index=False)